version: '3.8'

services:
  register-service:
    build:
      context: ./Register/app/register-service
      dockerfile: Dockerfile
    container_name: register-service
    ports:
      - "8081:8081"
    networks:
      - greencommerce-net

  login-service:
    build:
      context: ./Login/app/login-service
      dockerfile: Dockerfile
    container_name: login-service
    ports:
      - "8082:8082"
    networks:
      - greencommerce-net

networks:
  greencommerce-net:
    driver: bridge
