name: Deploy Authentication to AWS EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Authentication files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          source: |
            Backend/Domains/Authentication
          target: /home/ubuntu/GreenCommerce/Auth
          port: 22
          overwrite: true
          rm: true

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          script: |
            cd ~/GreenCommerce/Auth
            sudo docker-compose down --rmi all --volumes --remove-orphans || true
            sudo docker system prune -af || true
            sudo docker-compose up --build -d
