name: Deploy Authentication to AWS EC2

on:
  push:
    branches:
      - develop
    paths:
      - 'Backend/Domains/Authentication/Register/**'

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '17'

      - name: Build the JAR
        run: |
          cd Backend/Domains/Authentication/Register/app/register-service
          mvn clean package -DskipTests

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          port: 22
          # Copy directly into the remote target directory
          source: Backend/Domains/Authentication/Register/app/register-service/target/register-service-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/GreenCommerce/Backend/Domains/Authentication/Register/app/register-service/target/

      - name: Restart register-service on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          port: 22
          script_stop: false        # don’t abort on non-zero exit
          script: |
            cd /home/ubuntu/GreenCommerce/Backend/Domains/Authentication/Register/app/register-service/target
            # kill any running instance
            pkill -f 'java -jar register-service-0.0.1-SNAPSHOT.jar' || true
            # start in background; redirect logs to app.log
            nohup java -jar register-service-0.0.1-SNAPSHOT.jar > app.log 2>&1 &

