name: Deploy Authentication to AWS EC2

on:
  push:
    branches:
      - develop
    paths:
      - 'Backend/Domains/Authentication/Register/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: temurin
          java-package: jdk
          architecture: x64
          check-latest: false
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          overwrite-settings: true
          job-status: success

      - name: Build the JAR
        run: |
          cd Backend/Domains/Authentication/Register/app/register-service
          mvn clean package -DskipTests

      - name: Verify JAR files existence
        run: |
          ls Backend/Domains/Authentication/Register/app/register-service/target

      - name: Copy the JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          source: |
            Backend/Domains/Authentication/Register/app/register-service/target/register-service-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/GreenCommerce/
          port: 22
          overwrite: true

          
      - name: Execute JAR on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          script: |
            cd /home/ubuntu/GreenCommerce/Backend/Domains/Authentication/Register/app/register-service/target
            pkill -f 'java -jar register-service-0.0.1-SNAPSHOT.jar' || true
            java -jar register-service-0.0.1-SNAPSHOT.jar > /home/ubuntu/app.log 2>&1 &
          timeout: 3m