name: Deploy Authentication to AWS EC2

on:
  push:
    branches:
      - develop
    paths:
      - 'Backend/Domains/Authentication/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy Authentication files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          source: |
            Backend/Domains/Authentication
          target: /home/ubuntu/GreenCommerce/Auth
          port: 22
          overwrite: true
          rm: true

      - name: Create application.properties in EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_AUTH_HOST }}
          username: ${{ secrets.EC2_AUTH_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          script: |
            cd /home/ubuntu/GreenCommerce/Auth/Backend/Domains/Authentication/Login/app/login-service/src/main/resources

            echo "spring.application.name=LoginService" > application.properties
            echo "spring.datasource.url=${{ secrets.APP_DB_URL }}" >> application.properties
            echo "spring.datasource.username=${{ secrets.DB_USER }}" >> application.properties
            echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> application.properties
            echo "spring.datasource.initialization-mode=always" >> application.properties
            echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> application.properties
            echo "spring.jpa.defer-datasource-initialization=true" >> application.properties
            echo "spring.jpa.hibernate.ddl-auto=update" >> application.properties
            echo "spring.jpa.show-sql=true" >> application.properties
            echo "spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect" >> application.properties
            echo "server.port=8082" >> application.properties
            echo "jwt.secret=${{ secrets.JWT_SECRET }}" >> application.properties


            cd /home/ubuntu/GreenCommerce/Auth/Backend/Domains/Authentication
            sudo docker-compose down --rmi all --volumes --remove-orphans || true
            sudo docker system prune -af || true
            sudo docker-compose up --build -d
