name: Deploy ListUser from DockerHub to AWS EC2

on:
  push:
    branches:
      - develop
    paths:
      - 'Backend/Domains/Users/ListUser/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/list-user-service:latest ./Backend/Domains/Users/ListUser
          docker push ${{ secrets.DOCKER_USERNAME }}/list-user-service:latest

      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_USERS_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEYPAIR }}
          port: 22
          script: |
            # Detener y eliminar contenedor si existe
            sudo docker stop list-user-service || true
            sudo docker rm list-user-service || true

            # Eliminar imagen antigua
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/list-user-service:latest || true

            # Descargar la imagen actualizada desde Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/list-user-service:latest

            # Crear .env en la misma carpeta desde donde correremos el contenedor
            cd /home/ubuntu
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env  
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env

            # Verificar que .env no esté vacío
            if [ ! -s .env ]; then
              echo "ERROR: .env está vacío o no fue creado correctamente"
              exit 1
            fi

            # Ejecutar la nueva imagen con el .env
            sudo docker run -d --env-file .env -p 8081:8081 --name list-user-service ${{ secrets.DOCKER_USERNAME }}/list-user-service:latest
