name: Deploy Users (ImageUpload) to AWS EC2

on:
  push:
    branches:
      - develop
    paths:
      - 'Backend/Domains/Users/ImageUpload/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy ImageUpload files to EC2 (Users Domain)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_USERS_HOST }}
          username: ${{ secrets.EC2_USERS_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          source: |
            Backend/Domains/Users/ImageUpload
          target: /home/ubuntu/GreenCommerce
          port: 22
          overwrite: true
          rm: true

      - name: Deploy ImageUpload with Docker Compose
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_USERS_HOST }}
          username: ${{ secrets.EC2_USERS_USER }}
          key: ${{ secrets.EC2_AUTH_KEY }}
          script: |
            cd /home/ubuntu/GreenCommerce/Backend/Domains/Users/ImageUpload
            sudo docker-compose down --rmi all --volumes --remove-orphans || true
            sudo docker system prune -af || true
            sudo docker-compose up --build -d
